name: Java CI

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      isPreRelease:
        description: 'Is the build pre release?'     
        required: true
        default: true 
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'

      - name: Build with Maven
        working-directory: ./Project/SchoolTimetable
        run: mvn --batch-mode --update-snapshots -e -X package
      
      - name: Run the Maven verify phase
        working-directory: ./Project/SchoolTimetable
        run: mvn --batch-mode --update-snapshots -e -X verify
      
      - name: Run the Maven test phase
        working-directory: ./Project/SchoolTimetable
        run: mvn --batch-mode --update-snapshots -e -X test
        
      - run: mkdir staging && cp ./Project/SchoolTimetable/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
  
  publish_job:
    name: "Publish to release"
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Add tag data to enviroment
      run: echo "VERSION=0.0.1" >> $GITHUB_ENV

    - uses: actions/download-artifact@v2
      with:
        name: Package
        path: staging

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{env.VERSION}}"
        prerelease: true # ${{ github.event.inputs.isPreRelease }}
        title: Build ${{env.VERSION}}
        files: |
            staging/*
